cache:
  pip: true

language:
  python

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO=22
  - DJANGO=30

install:
  - pip install tox
  - export TOXENV=py${TRAVIS_PYTHON_VERSION//./}-django${DJANGO}

script:
  - tox -e ${TOXENV}
