cache:
  pip: true

language:
  python

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

env:
  - DJANGO=22
  - DJANGO=32
  - DJANGO=40

jobs:
  exclude:
  - python: 3.6
    env: DJANGO=40
  - python: 3.7
    env: DJANGO=40

install:
  - pip install tox
  - export TOXENV=py${TRAVIS_PYTHON_VERSION//./}-django${DJANGO}

script:
  - tox -e ${TOXENV}
